# Generated by Django 5.1.6 on 2025-02-08 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter your full name.', max_length=100, verbose_name='Full Name')),
                ('password', models.CharField(help_text='Store hashed passwords securely.', max_length=128, verbose_name='Password')),
                ('manager_id', models.PositiveIntegerField(blank=True, help_text='ID of the manager if applicable.', null=True, verbose_name='Manager ID')),
                ('nric', models.CharField(help_text='Enter a valid NRIC (unique).', max_length=12, unique=True, verbose_name='NRIC')),
                ('phone_number', models.CharField(help_text='Enter a valid phone number.', max_length=15, unique=True, verbose_name='Phone Number')),
                ('email', models.EmailField(help_text='Enter a valid email address.', max_length=254, unique=True, verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Account Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
            ],
        ),
    ]
