# Generated by Django 5.1.6 on 2025-02-09 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_application_application_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='inspection_date',
            field=models.DateField(null=True, verbose_name='Inspection Date'),
        ),
        migrations.AddField(
            model_name='application',
            name='inspection_location',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='inspection_time',
            field=models.CharField(max_length=100, null=True, verbose_name='Inspection Time'),
        ),
        migrations.AddField(
            model_name='application',
            name='inspector',
            field=models.CharField(max_length=100, null=True, verbose_name='inspector assign'),
        ),
    ]
