# Generated by Django 5.1.6 on 2025-02-09 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_application_inspection_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='inspection_date',
            field=models.DateField(blank=True, null=True, verbose_name='Inspection Date'),
        ),
        migrations.AlterField(
            model_name='application',
            name='inspection_location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='inspection_time',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Inspection Time'),
        ),
        migrations.AlterField(
            model_name='application',
            name='inspector',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='inspector assign'),
        ),
        migrations.AlterField(
            model_name='hawker',
            name='hawker_id',
            field=models.CharField(max_length=5, verbose_name='Hawker ID'),
        ),
    ]
