# Generated by Django 5.1.6 on 2025-02-10 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_alter_application_inspection_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hawker',
            name='email',
            field=models.EmailField(blank=True, help_text='Enter a valid email address.', max_length=254, null=True, unique=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='hawker',
            name='password',
            field=models.CharField(blank=True, help_text='Store hashed passwords securely.', max_length=128, null=True, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='hawker',
            name='hawker_id',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='NRIC'),
        ),
    ]
