# Generated by Django 5.1.6 on 2025-02-10 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_hawker_email_hawker_password_alter_hawker_hawker_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='application_date',
        ),
        migrations.RemoveField(
            model_name='application',
            name='application_id',
        ),
        migrations.AddField(
            model_name='application',
            name='approval_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='business_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='business_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='email',
            field=models.EmailField(blank=True, help_text='Enter a valid email address.', max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='application',
            name='food_handling_cert',
            field=models.FileField(blank=True, null=True, upload_to='uploads/food_handling_cert/'),
        ),
        migrations.AddField(
            model_name='application',
            name='fullname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='home_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='license_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='nationality',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='nric',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='nric_document',
            field=models.FileField(blank=True, null=True, upload_to='uploads/nric_documents/'),
        ),
        migrations.AddField(
            model_name='application',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('unpaid', 'UNPAID'), ('paid', 'PAID')], default='pending', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='race',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='schedule_status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('not_scheduled', 'Not Scheduled')], default='not_scheduled', max_length=15),
        ),
        migrations.AddField(
            model_name='application',
            name='stall_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='submission_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='verification_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='application_status',
            field=models.CharField(blank=True, choices=[('pending', 'PENDING'), ('approved', 'APPROVED'), ('rejected', 'REJECTED')], default='pending', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='hawker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='polls.hawker'),
        ),
    ]
