# Generated by Django 5.1.6 on 2025-02-10 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_remove_license_business_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('inspector_id', models.CharField(max_length=50, unique=True)),
                ('nric', models.CharField(max_length=20, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='application',
            name='inspection_date',
        ),
        migrations.RemoveField(
            model_name='application',
            name='inspection_location',
        ),
        migrations.RemoveField(
            model_name='application',
            name='inspection_time',
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_location', models.CharField(blank=True, max_length=200, null=True)),
                ('inspection_date', models.DateField(blank=True, null=True, verbose_name='Inspection Date')),
                ('inspection_time', models.CharField(blank=True, max_length=100, null=True, verbose_name='Inspection Time')),
                ('inspection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspection', to='polls.application')),
                ('inspector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspector', to='polls.inspector')),
            ],
        ),
    ]
