# Generated by Django 5.1.6 on 2025-02-10 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_rename_inspection_inspection_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='status_inspection',
            field=models.CharField(blank=True, choices=[('done', 'DONE'), ('not yet', 'not_yet')], default='not yet', max_length=10, null=True),
        ),
    ]
