# Generated by Django 5.1.6 on 2025-02-10 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_inspection_status_inspection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspection',
            name='inspection_location',
        ),
    ]
