# Generated by Django 5.1.6 on 2025-02-10 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_remove_inspection_inspection_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='inspection_time',
            field=models.TimeField(blank=True, max_length=100, null=True, verbose_name='Inspection Time'),
        ),
    ]
