# Generated by Django 5.1.6 on 2025-02-10 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_alter_inspection_inspection_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspection',
            name='inspection_time',
        ),
        migrations.AlterField(
            model_name='inspection',
            name='inspection_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Inspection Date'),
        ),
    ]
