# Generated by Django 5.1.6 on 2025-02-10 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0018_remove_inspection_inspection_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='inspection_time',
            field=models.TimeField(blank=True, max_length=100, null=True, verbose_name='Inspection Time'),
        ),
    ]
