# Generated by Django 5.1.6 on 2025-02-10 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0019_inspection_inspection_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspector_id', models.CharField(blank=True, max_length=50, null=True)),
                ('inspection_id', models.CharField(max_length=50, unique=True)),
                ('location', models.CharField(max_length=255)),
                ('date_inspect', models.DateField()),
                ('result', models.CharField(choices=[('Pass', 'Pass'), ('Fail', 'Fail')], max_length=10)),
                ('fines', models.TextField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='inspection',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='result',
            field=models.CharField(blank=True, choices=[('Pass', 'Pass'), ('Fail', 'Fail')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='inspection_date',
            field=models.DateField(blank=True, null=True, verbose_name='Inspection Date'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='status_inspection',
            field=models.CharField(blank=True, choices=[('done', 'done'), ('not yet', 'not_yet')], default='not yet', max_length=10, null=True),
        ),
    ]
