# Generated by Django 5.1.6 on 2025-02-11 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0020_emergencyinspection_inspection_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencyinspection',
            name='inspection_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='emergencyinspection',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='inspector',
            name='inspector_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='inspector',
            name='nric',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
