# Generated by Django 5.1.6 on 2025-02-11 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0021_alter_emergencyinspection_inspection_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='inspection_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
