# Generated by Django 5.1.6 on 2025-02-11 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0022_inspection_inspection_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='application_status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('inspected', 'INSPECTED'), ('approved', 'APPROVED'), ('rejected', 'REJECTED')], default='pending', max_length=15),
        ),
    ]
