# Generated by Django 5.1.6 on 2025-02-11 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0024_emergencyinspection_application_fines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='inspector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspection', to='polls.inspector'),
        ),
    ]
