# Generated by Django 5.1.6 on 2025-02-11 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0025_alter_inspection_inspector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergencyinspection',
            name='inspector_id',
        ),
    ]
