# Generated by Django 5.1.6 on 2025-02-12 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0027_emergencyinspection_fines_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='license_id',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.CreateModel(
            name='Renewal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('business_changes', models.CharField(blank=True, max_length=500, null=True)),
                ('document_update', models.FileField(blank=True, null=True, upload_to='uploads/document_update/')),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='renewal', to='polls.application')),
                ('hawker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='renewal', to='polls.hawker')),
            ],
        ),
    ]
