# Generated by Django 5.1.6 on 2025-02-12 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0028_alter_license_license_id_renewal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspector',
            name='nric',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
