# Generated by Django 5.1.6 on 2025-02-12 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0029_alter_inspector_nric_delete_choice_delete_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='manager_id',
            field=models.CharField(blank=True, help_text='ID of the manager if applicable.', max_length=100, null=True, verbose_name='Manager ID'),
        ),
    ]
