# Generated by Django 5.1.6 on 2025-02-12 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0030_alter_signup_manager_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('unpaid', 'UNPAID'), ('paid', 'PAID')], default='unpaid', max_length=10, null=True),
        ),
    ]
