# Generated by Django 5.1.6 on 2025-02-12 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0031_alter_application_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fines',
            name='due_date',
        ),
    ]
